theme: minima
header_pages: ['']
title: Contact information
author: Vasiliy Aboymov
email: aboymov at gmail.com
show_excerpts: true
description: > 
  About me and my work

github_username:  stee1rat
linkedin_username: aboymov
