theme: minima
header_pages: ['']
title: My user page
author: test
email: test@gmail.com
show_excerpts: true
description: > 
  About me and my work

twitter_username: stee1rat 
github_username:  aboymov
instagram_username: jekyll
linkedin_username: jekyll
