theme: minima
header_pages: ['']
title: My user page
author: test
email: test@gmail.com
show_excerpts: true
description: > 
  About me and my work

twitter_username: jekyllrb
github_username:  jekyll
dribbble_username: jekyll
facebook_username: jekyll
flickr_username: jekyll
instagram_username: jekyll
linkedin_username: jekyll
pinterest_username: jekyll
youtube_username: jekyll
googleplus_username: +jekyll
rss: rss
